import db from './index';
import { videos } from './schema';

async function seed() {
  await db.delete(videos); // Vide la table pour éviter les doublons lors du seed
  await db.insert(videos).values([
    {
      title: 'React Avancé',
      slug: 'react-avance',
      category: 'Développement Web',
      thumbnail: '/thumbnails/react-advanced.png',
      videoUrl: 'https://www.youtube.com/embed/Ke90Tje7VS0',
      description: 'Approfondissez vos connaissances sur React avec des concepts avancés.'
    },
    {
      title: 'Découverte de Next.js',
      slug: 'decouverte-nextjs',
      category: 'Développement Web',
      thumbnail: '/thumbnails/nextjs.png',
      videoUrl: 'https://www.youtube.com/embed/Sklc_fQBmcs',
      description: 'Introduction au framework Next.js pour des applications React server-side.',
    },
    {
      title: 'Bases de TypeScript',
      slug: 'bases-typescript',
      category: 'Développement Web',
      thumbnail: '/thumbnails/typescript.png',
      videoUrl: 'https://www.youtube.com/embed/BwuLxPH8IDs',
      description: 'Apprenez les bases de TypeScript pour des projets robustes.',
    },
    {
      title: 'Node.js pour débutants',
      slug: 'nodejs-debutants',
      category: 'Backend',
      thumbnail: '/thumbnails/nodejs.png',
      videoUrl: 'https://www.youtube.com/embed/TlB_eWDSMt4',
      description: 'Premiers pas avec Node.js et le développement backend.',
    },
    {
      title: 'Express.js Essentials',
      slug: 'expressjs-essentials',
      category: 'Backend',
      thumbnail: '/thumbnails/expressjs.png',
      videoUrl: 'https://www.youtube.com/embed/L72fhGm1tfE',
      description: 'Tout savoir sur Express.js pour créer des APIs REST.',
    },
    {
      title: 'MongoDB Introduction',
      slug: 'mongodb-intro',
      category: 'Base de données',
      thumbnail: '/thumbnails/mongodb.png',
      videoUrl: 'https://www.youtube.com/embed/pWbMrx5rVBE',
      description: 'Introduction à la base de données NoSQL MongoDB.',
    },
    {
      title: 'SQL pour débutants',
      slug: 'sql-debutants',
      category: 'Base de données',
      thumbnail: '/thumbnails/sql.png',
      videoUrl: 'https://www.youtube.com/embed/7S_tz1z_5bA',
      description: 'Apprenez les bases du langage SQL.',
    },
    {
      title: 'HTML5 Complet',
      slug: 'html5-complet',
      category: 'Développement Web',
      thumbnail: '/thumbnails/html5.png',
      videoUrl: 'https://www.youtube.com/embed/qz0aGYrrlhU',
      description: 'Un tour complet des nouveautés HTML5.',
    },
    {
      title: 'CSS3 Moderne',
      slug: 'css3-moderne',
      category: 'Développement Web',
      thumbnail: '/thumbnails/css3.png',
      videoUrl: 'https://www.youtube.com/embed/1Rs2ND1ryYc',
      description: 'Techniques modernes de mise en page CSS3.',
    },
    {
      title: 'Flexbox et Grid',
      slug: 'flexbox-grid',
      category: 'Développement Web',
      thumbnail: '/thumbnails/flexbox-grid.png',
      videoUrl: 'https://www.youtube.com/embed/JJSoEo8JSnc',
      description: 'Comprendre Flexbox et CSS Grid pour des layouts responsives.',
    },
    {
      title: 'JavaScript ES6+',
      slug: 'javascript-es6',
      category: 'Développement Web',
      thumbnail: '/thumbnails/js-es6.png',
      videoUrl: 'https://www.youtube.com/embed/NCwa_xi0Uuc',
      description: 'Les nouveautés de JavaScript ES6 et versions ultérieures.',
    },
    {
      title: 'Vue.js pour débutants',
      slug: 'vuejs-debutants',
      category: 'Développement Web',
      thumbnail: '/thumbnails/vuejs.png',
      videoUrl: 'https://www.youtube.com/embed/4deVCNJq3qc',
      description: 'Commencez avec Vue.js et ses concepts fondamentaux.',
    },
    {
      title: 'Angular Essentials',
      slug: 'angular-essentials',
      category: 'Développement Web',
      thumbnail: '/thumbnails/angular.png',
      videoUrl: 'https://www.youtube.com/embed/2OHbjep_WjQ',
      description: 'Les bases pour démarrer avec Angular.',
    },
    {
      title: 'Sass & SCSS',
      slug: 'sass-scss',
      category: 'Développement Web',
      thumbnail: '/thumbnails/sass.png',
      videoUrl: 'https://www.youtube.com/embed/_a5j7KoflTs',
      description: 'Préprocesseur CSS : Sass et SCSS.',
    },
    {
      title: 'Bootstrap Rapide',
      slug: 'bootstrap-rapide',
      category: 'Développement Web',
      thumbnail: '/thumbnails/bootstrap.png',
      videoUrl: 'https://www.youtube.com/embed/-qfEOE4vtxE',
      description: 'Créer des interfaces rapidement avec Bootstrap.',
    },
    {
      title: 'Git & GitHub',
      slug: 'git-github',
      category: 'Outils',
      thumbnail: '/thumbnails/git-github.png',
      videoUrl: 'https://www.youtube.com/embed/RGOj5yH7evk',
      description: 'Gérer son code source avec Git et GitHub.',
    },
    {
      title: 'Docker pour débutants',
      slug: 'docker-debutants',
      category: 'DevOps',
      thumbnail: '/thumbnails/docker.png',
      videoUrl: 'https://www.youtube.com/embed/3c-iBn73dDE',
      description: 'Découverte de la conteneurisation avec Docker.',
    },
    {
      title: 'CI/CD avec GitHub Actions',
      slug: 'cicd-github-actions',
      category: 'DevOps',
      thumbnail: '/thumbnails/cicd.png',
      videoUrl: 'https://www.youtube.com/embed/eB0nUzAI7M8',
      description: 'Automatisez vos déploiements avec GitHub Actions.',
    },
    {
      title: 'Python pour débutants',
      slug: 'python-debutants',
      category: 'Développement',
      thumbnail: '/thumbnails/python.png',
      videoUrl: 'https://www.youtube.com/embed/kqtD5dpn9C8',
      description: 'Premiers pas avec le langage Python.',
    },
    {
      title: 'Pandas Essentials',
      slug: 'pandas-essentials',
      category: 'Data Science',
      thumbnail: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=400&q=80',
      videoUrl: 'https://www.youtube.com/embed/vmEHCJofslg',
      description: 'Manipulation de données avec Pandas.',
    },
    {
      title: 'Machine Learning Intro',
      slug: 'ml-intro',
      category: 'Data Science',
      thumbnail: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=400&q=80',
      videoUrl: 'https://www.youtube.com/embed/GwIo3gDZCVQ',
      description: 'Introduction au Machine Learning.',
    },
    {
      title: 'Power BI Basics',
      slug: 'powerbi-basics',
      category: 'Data Science',
      thumbnail: '/thumbnails/powerbi.png',
      videoUrl: 'https://www.youtube.com/embed/AGrl-H87pRU',
      description: 'Visualisation de données avec Power BI.',
    },
    {
      title: 'SEO Fondamentaux',
      slug: 'seo-fondamentaux',
      category: 'Marketing',
      thumbnail: '/thumbnails/seo.png',
      videoUrl: 'https://www.youtube.com/embed/ysEN5RaKOlA',
      description: 'Optimisez votre site pour les moteurs de recherche.',
    },
    {
      title: 'Figma pour débutants',
      slug: 'figma-debutants',
      category: 'Design',
      thumbnail: '/thumbnails/figma.png',
      videoUrl: 'https://www.youtube.com/embed/jwCmIBJ8Jtc',
      description: 'Premiers pas avec Figma pour le design UI/UX.'
    },

    {
      title: 'WordPress de A à Z',
      slug: 'wordpress-a-z',
      category: 'Développement Web',
      thumbnail: '/thumbnails/wordpress.png',
      videoUrl: 'https://www.youtube.com/embed/8AZ8GqW5iak',
      description: 'Créer et gérer un site WordPress complet.',
      
    },
  ]);
  console.log('Seed terminé !');
}

seed();
